on:
  workflow_dispatch:
    inputs:
      tfvars:
        description: 'tfvars file'
        required: true
        default: 'staging'
        type: choice
        options:
        - prod
        - staging

jobs:
  test-input-variables:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "environment/$TFVARS.auto.tfvars"
          
        env:
          TFVARS: ${{ github.event.inputs.tfvars }}
          
